---
title: Operational Notes
date: "`r Sys.Date()`"
output: docx
---

## From Maria
4 studies including males only: Sthoeger 1987. Folomeev 1990, Kaufman 1989, Chang 1995.
Also, Grigor should be excluded  (same cohort as Hohmeister).

## Studies

+ Remove Rodriguez (2000) from study

## KM's

Voss is not a KM since it's x-axis is age, not years.
Updated Heller digitization, since it was wrong (12/1/16)

Several studies have arms in different epochs: Urman, Uramoto, Rodriguez, and Funauchi

N's were off for multi-arm trials, due to Voss leaving and Funauchi being separated.

## Plots

+ Pokroy-Shapiro's plots are for renal survival. It will go into
just follow-up data with 11.3% survival rate overall. (12/14/16)
+ Digitize Ginzler Fig1 for the study (12/14/16)

## Digitized Plots

Several plots are really survival estimates and not KM plots

More importantly, many plots are labeled "Time from diagnosis". These plots
should be treated as time from diagnosis, and the lag should be 0. This was
computed in DataMunging.R and incorporated in final_study_info.rda


## Study duration

We're taking Estes to be 1961-1969 based on very sketchy information in the paper.
